<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books [
<!ELEMENT books (book*)>
<!ELEMENT book (name, phone, e-mail, company)>
    <!ELEMENT name (#PCDATA)>
    <!ATTLIST book address (street|no|zip|country) #REQUIRED>
    <!ELEMENT phone (#PCDATA)>
    <!ELEMENT e-mail (#PCDATA)*>
    <!ELEMENT company (comp_name, list)>
    <!ELEMENT comp_name (#PCDATA)>
    <!ELEMENT list (site, URL)>
    <!ELEMENT site (#PCDATA)>
    <!ELEMENT URL (#PCDATA)>
]>

<books>
  <book address="street">
    <name>pedro lope</name>
    <phone>6758238</phone>
    <e-mail>pedro@gmail.com</e-mail>
    <company>
      <comp_name>pedri</comp_name>
      <list>
        <site>pedro.com</site>
        <URL>https://www.pedro.es</URL>
      </list>
    </company>
  </book>
</books>